### ISSUE TITLE
Caratteri speciale

### ISSUE THREAD

**Issue by rekhyt75** [rekhyt75/BrewPlus-IFDB#1]
Caratteri speciali non correttamente visualizzati

**Comment by aperuzzi** [comment]
Lista file ancora con caratteri sporchi

**brewplus-ifdb**
- `jmash.component.JGravitySpinner.java` --> riga 32
- `jmash.tableModel.FermentationLogTableModel.java` --> riga 34
- `jmash.tableModel.SummaryTableModel.java` --> righe 35, 57, 194
- `jmash.frmFeed2.java` --> righe 190, 192, 193, 194, 195, 196, 197, 198
- `jmash.YeastPitching.java` --> riga 151

**brewplus-ifdb-distr**
- `src/main/resources/distr/config/NoteB.note` --> riga 1
