### ISSUE TITLE
Valore pH e gestione sali

### ISSUE THREAD

**Issue by JigenDaisuke** [rekhyt75/BrewPlus-IFDB#10]
Implementare la funzione pH nella schermata della realizzazione delle ricetta, una volta impostati i valori dell'acqua che si tulizza e man mano che si aggiungono i grani si deve avere la finestra del valore del pH dell'acqua e se possibile far uscire la quantità di acido lattico/citrico da inserire per avere quello ottimale o in alternativa mettere tra gli ingredienti "additivi" che andranno a variare il valore del pH e dell'acqua.

**Comment by aperuzzi** [comment]
Bisogna inoltre creare un nuovo tabellame "Categoria malti" in cui per ora ci sono 3 campi: codice, nome ph

Il ph verrà adoperato per fare i conti

Inoltre ad ogni malto specifico si dovrà associare la categoria... e vai col lavoraccio.. per ora abbiamo oltre 120 tipi di fermentabili e saranno da associare.

**Comment by JigenDaisuke** [comment]
Secondo me occorre inserire il valore pH nella tabella dei malti oppure associare ai malti del'XML una categoria alla quale fà riferimento il pH.

**Comment by mr-sgabuzen** [comment]
Sezione ricette: inserimento volume "desiderato" (in fermentatore) ----> questo valore viene utilizzato nella schermata "quantità acqua" per calcolare il volume totale da utilizzare (ag o biab) -----> quantità acqua viene caricata nella schermata "qualità"... tutto deve essere collegato. ;)
