### ISSUE TITLE
Errore "java.lang... " quando si inserisce il valore 'attenuazione' del lievito

### ISSUE THREAD

**Issue by Batigolle** [rekhyt75/BrewPlus-IFDB#23]
Quando si tenta di inserire il valore dell'attenuazione del lievito scelto,
 nella scheda 'Lievito e fermentazione' si ottiene il seguente errore a video 
"java.lang.ClassCastException: Cannot cast java.lang.String to java.lang.Integer"

Allego log del programma
[BrewPlus-IFDB.zip](https://github.com/rekhyt75/BrewPlus-IFDB/files/314920/BrewPlus-IFDB.zip)

**Comment by Drunkypiggy** [comment]
questo errore penso sia la conseguenza della issues 22 o viceversa...
quando ho aggiornato il file dei lieviti volevo inserirgli anche l'attenuazione e la temp ma non me li prendeva...
