### ISSUE TITLE
Parametro locale in config

### ISSUE THREAD

**Issue by girella** [rekhyt75/BrewPlus-IFDB#24]
Il parametro "locale" nel file config.xml non viene gestito nel salvataggio della configurazione.
Quindi se si cambiamo le impostazioni e poi si salvano questo elemento viene perso mandando
in errore l'applicazione

**Comment by girella** [comment]
Risolta la scrittura e lettura del parametro da file xml ma manca comunque la gestione da 
maschera delle impostazioni.

**Comment by rekhyt75** [comment]
BJCP non funziona più.
Correggere gestione localization
