### ISSUE TITLE
Bug Anteprima Stampa - Lievito e Fermentazione

### ISSUE THREAD

**Issue by vitofasano** [rekhyt75/BrewPlus-IFDB#35]
Secondo Bug segnalato da Denosoc
Link: http://www.ilforumdellabirra.net/viewtopic.php?f=37&t=8830#p85912

riporto:

> Un piccolo bug che segnalo è questo: nell'anteprima di stampa non vengono riportate le note scritte nella sezione "lievito e fermentazione" nell'apposito spazio sotto al taccuino.

**Comment by girella** [comment]
In realtà la sezione note della stampa non è legata a quella della sezione fermentazione.
