### ISSUE TITLE
Rapporto bu/gu min e max

### ISSUE THREAD

**Issue by vitofasano** [rekhyt75/BrewPlus-IFDB#37]
Bug segnalato da houston per conto di un amico.
http://www.ilforumdellabirra.net/viewtopic.php?f=37&t=8830#p85916

Riporto:

> è possibile inserire una finestra di dialogo nella schermata della ricetta con rapporto bu/gu min e max?

**Comment by rekhyt75** [comment]
deferred
Esistono gia i valori di IBU e OG min e max
