### ISSUE TITLE
Tabelle (quantità e attenuazione) non compilate

### ISSUE THREAD

**Issue by vitofasano** [rekhyt75/BrewPlus-IFDB#40]
Secondo bug segnalato da christiantilt
http://www.ilforumdellabirra.net/viewtopic.php?f=37&t=8830#p85919

Riporto:

> Inoltre nella pagina con la scheda ricetta da stampare, nella sezione dedicata al lievito, compaiono due tabelle (quantità e attenuazione) che non vengono compilate in automatico (essendo dati noti, mi aspetterei che il software le compilasse).

**Comment by girella** [comment]
L'attenuazione dovrebbe essere compilata per ogni lievito nel file lieviti.xml. 
Per la quantità andrebbe aggiunta una colonna nella sezione dei "lieviti e fermentazione" relativa alla ricetta.
