### ISSUE TITLE
IBU rager non visualizzate

### ISSUE THREAD

**Issue by vitofasano** [rekhyt75/BrewPlus-IFDB#43]
Secondo Bug segnalato da tony10
http://www.ilforumdellabirra.net/viewtopic.php?f=37&t=8830#p85933

Riporto:

> Le IBU le calcola in tinseth mentre nelle impostazioni le ho settato in rager.

PS: penso che intenda le IBU visualizzate nell'anteprima di stampa

**Comment by girella** [comment]
Il settaggio riguarda il rapporto tra BU/GU e non come vanno espresse le IBU.
Potrei prendere questa impostazione anche per il valore da utilizzare per l'unita di misura dell'IBU nella stampa .
