### ISSUE TITLE
Ubuntu: non funzionano alcune icone/tools

### ISSUE THREAD

**Issue by vitofasano** [rekhyt75/BrewPlus-IFDB#45]
Bug su Ubuntu segnalato da mbtorre
http://www.ilforumdellabirra.net/viewtopic.php?f=37&t=8830&start=10#p85966

Riporto:

> cliccando sull'icona parte ma non funziona (es. non si apre Nuova Ricetta, Impostazioni, Apri, Registrazione Cotte).

**Comment by girella** [comment]
Su Ubuntu 16 funziona correttamente. Per la segnalazione di errori andrebbe richiesto il file di log.

**Comment by vitofasano** [comment]
l'ho richiesto. aspettiamo se risponde.

**Comment by rekhyt75** [comment]
no updates 
issue non replicabile
