### ISSUE TITLE
Ordine grani in base al peso

### ISSUE THREAD

**Issue by vitofasano** [rekhyt75/BrewPlus-IFDB#47]
Secondo Bug segnalato da theguardian_it
http://www.ilforumdellabirra.net/viewtopic.php?f=37&t=8830&start=10#p85968

Riporto:

> se nella ricetta provo ad ordinare i grani in base al peso, non vengono ordinati correttamente. Per capirci, ordinandoli dal più grande al più piccolo mette cose tipo 2.500 grammi come maggiore di 6.600 grammi, idem dal più piccolo al più grande, 6.600 grammi considerati inferiori a 2.500 (o a 3.200 di un altro malto). Se si ordina per percentuale, invece, è tutto ok.

**Comment by DiegoDellaBotte** [comment]
Attendo un test anche da parte vostra così la chiudiamo
