### ISSUE TITLE
Filtri per schede dei luppoli

### ISSUE THREAD

**Issue by vitofasano** [rekhyt75/BrewPlus-IFDB#49]
Proposte segnalate da theguardian_it
http://www.ilforumdellabirra.net/viewtopic.php?f=37&t=8830&start=10#p85968

Riporto:

> Sarebbe utile, poi, inserire un filtro nelle schede dei luppoli, per consentire (così come viene fatto per grani/estratto/cristalli per il malto) di dividere i luppoli per Amaro, Aroma, o Entrambi.
> In futuro, ovviamente, potrebbe essere perfino utile dividerli per macrocategorie filtrabili (erbaceo, floreale, agrumato, speziato, ecc.).

**Comment by DiegoDellaBotte** [comment]
Committato su branch feature/filtro-ricerca-luppoli
