### ISSUE TITLE
Quantità acqua nel foglio di stampa

### ISSUE THREAD

**Issue by JigenDaisuke** [rekhyt75/BrewPlus-IFDB#9]
Inserire nel foglio di stampa le quantità di acqua necessaria (varie pentole se classica o singola pentola se biab ecc...).

**Comment by girella** [comment]
Propongo di eliminare dalla stampa il grafico per far entrare tutto su una pagina e poi aggiungiamo le quantità.

**Comment by girella** [comment]
I dati dell'acqua vanno presi dal profilo dell'impianto

**Comment by girella** [comment]
Rilasciata nella versione 2.0.0
